#!/bin/sh
APPDIR=`dirname $0`;
java -Xmx256M  -cp "$APPDIR/src:$APPDIR/bin:./lib/gxt.jar:/home/bmalkow/programs/gwt-linux-1.5.0/gwt-user.jar:/home/bmalkow/programs/gwt-linux-1.5.0/gwt-dev-linux.jar" com.google.gwt.dev.GWTShell -out "$APPDIR/www" "$@" tigase.messenger.Messenger/Messenger.html;
