#!/bin/sh
APPDIR=`dirname $0`;
java  -cp "$APPDIR/src:$APPDIR/bin:/home/bmalkow/programs/gwt-linux-0.0.2030/gwt-user.jar:/home/bmalkow/programs/gwt-linux-0.0.2030/gwt-dev-linux.jar" com.google.gwt.dev.GWTShell -out "$APPDIR/www" "$@" tigase.messenger.Messenger/Messenger.html;
